config/routes.rb
Rails.application.routes.draw do
  get 'techskills/new'
  root 'employees#index'
  resources :employees
  resources :techskills, only: [:new, :create, :destroy]
  resources :firms, only: [:new, :create, :destroy]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/employee.rb
class Employee < ApplicationRecord
      has_many :firms
      has_many :techskills, through: :firms
      validates :emp_id, presence: true
      validates :emp_id, uniqueness:true
end

app/models/firm.rb
class Firm < ApplicationRecord
      belongs_to :employee
      belongs_to :techskill
end

app/models/techskill.rb
class Techskill < ApplicationRecord
      has_many :firms
      has_many :employees, through: :firms
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
 def index
      @employees=Employee.all
  end

  def new
      @employee=Employee.new
  end

  def create
    @employee=Employee.create(params.require(:employee).permit(:emp_id,:company_id,:name,:status))
    if @employee.valid?
       redirect_to employees_path
    else
    	flash[:errors] =@employee.errors.full_messages
    	redirect_to new_employee_path      
    end
  end

  def show
      @employee=Employee.find(params[:id])
  end

  def edit
      @employee= Employee.find(params[:id])
  end

  def update
      @employee= Employee.find(params[:id])
      @employee= Employee.update(params.require(:employee).permit(:emp_id,:company_id,:name,:status))
      @employee= Employee.find(params[:id])
      redirect_to employee_path(@employee)	
  end

  def destroy
      @employee= Employee.find(params[:id])
      @employee.destroy
      redirect_to employees_path
  end

  private
  def employee_params
      params.require(:employee).permit(:emp_id,:company_id,:name,:status)
  end
end

app/controllers/firms_controller.rb
class FirmsController < ApplicationController
 def index
  end

  def new
      @firm=Firm.new
  end

  def create
    @firm=Firm.create(params.require(:firm).permit(:employee_id,:techskill_id,:name,:verified))
    redirect_to employee_path(@firm.employee)
  end
  def destroy
      @firm= Firm.find(params[:id])
      @employee=@firm.employee
      @firm.destroy
      redirect_to employee_path(@employee)
  end
end

app/controllers/techskills_controller.rb
class TechskillsController < ApplicationController
 def index
  end

  def new
      @techskill=Techskill.new
  end

  def create
    @techskill=Techskill.create(params.require(:techskill).permit(:name))
    redirect_to employee_path(@techskill.employee)
  end
  def destroy
      @techskill= Techskill.find(params[:id])
      @employee=@techskill.employee
      @techskill.destroy
      redirect_to employee_path(@employee)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/firms_helper.rb
module FirmsHelper
end

app/helpers/techskills_helper.rb
module TechskillsHelper
end

app/views/employees/create.html.erb
<h1>Employees#create</h1>
<p>Find me in app/views/employees/create.html.erb</p>

app/views/employees/destroy.html.erb
<h1>Employees#destroy</h1>
<p>Find me in app/views/employees/destroy.html.erb</p>

app/views/employees/edit.html.erb
<div class="container">
<div class="row justify-content-center">
<h1 clas="mt-4 mb-4 display-4">Edit Employee details</h1>
</div>
<br>
<br>
<br>
<div class="row justify-content-center">
<%= form_with( model: @employee,local:true) do |f|%>
<div class="form-group">
    <%= f.label :emp_id%><hr>&emsp;</hr>
    <%= f.text_field :emp_id %>
</div>
<div class="form-group">
    <%= f.label :company_id%><hr>&nbsp;</hr>
    <%= f.text_field :company_id %>
 </div>   
<div class="form-group">
    <%= f.label :name%><hr>&ensp;</hr>
    <%= f.text_field :name %>
</div>
<div class="form-group">
    <%= f.label :status%><hr>&ensp;</hr>
    <%= f.text_field :status %>
 </div>
 <div class="form-group">   
    <%=f.submit 'Update',:class => 'btn btn-dark' %>
    <%= hidden_field_tag :prev_page, f.submit %>
 </div>
 <%end%>
 </div>
 </div>

app/views/employees/index.html.erb
<div class="container">
<br>
<br>
<br>
<div class="row justify-content-center">
<h1>Employees Corner</h1></div>
<br>
<br>
<br>
<br>
<div class="row justify-content-center">
<%= button_to "Add New Employee", new_employee_path,method: :get , class:"btn btn-dark"%></div>
<br>
<br>
<br>
<br>
<div class="row justify-content-center">
<table class="table table-bordered">
<thead>
<tr>
<th scope="col" style="text-align: center">Employee</th>
<th scope="col" style="text-align: center">Emp Id</th>
<th scope="col" style="text-align: center">Action</th>
</tr>
</thead>
<tbody>
<% @employees.each do |employee|%>
<tr>
<td style="text-align: center"><%=employee.name%></td>
<td style="text-align: center"><%=employee.emp_id%></td>
<td style="text-align: center"><%=button_to "Show"  ,employee_path(employee),method: :get   , class:"btn btn-dark"%></td>
</tr>
<% end %>
</tbody>
</table>
</div>

app/views/employees/new.html.erb
<div class="container">
<div class="row justify-content-center">
<h1 clas="mt-4 mb-4 display-4">Employees Form</h1>
</div>
<% if flash[:errors]%>
   <% flash[:errors].each do |error|%>
   	<p style="color: red"><%= error%></p>
   <%end%>
<%end%>
<br>
<br>
<br>
<div class="row justify-content-center">
<%= form_for @employee do |f|%>
<div class="form-group">
    <%= f.label :"Employee-id"%><hr>&emsp;</hr>
    <%= f.text_field :emp_id %>
</div>
<div class="form-group">
    <%= f.label :"Company-id"%><hr>&nbsp;</hr>
    <%= f.text_field :company_id %>
 </div>   
<div class="form-group">
    <%= f.label :name%><hr>&ensp;</hr>
    <%= f.text_field :name %>
</div>
<div class="form-group">
    <%= f.label :status%><hr>&ensp;</hr>
    <%= f.text_field :status %>
 </div>
 <div class="form-group">   
   <%=f.submit 'Save Details',:class => 'btn btn-dark' %>
 </div>
 <%end%>
 </div>
 </div>

app/views/employees/show.html.erb
<div class="container">
<div class="row justify-content-center">
<h1 clas="mt-4 mb-4 display-4"><%= @employee.name%>'s Details</h1></div>
<br>
<p><h4>Employee id: <%= @employee.emp_id%></h4></p>
<p><h4>Company id: <%= @employee.company_id%></h4></p>
<p><h4>Status: <%= @employee.status%></h4></p>
</div>
<br>
<div class="row justify-content-center"><h2>Tech Stack</h2></div>
<br>
<div class="row justify-content-center">
<%= button_to "Choose your techskills",new_firm_path, method: :get , class:"btn btn-dark"%><br></div>
<br>
<div class="row justify-content-center">
<table class="table table-bordered">
<thead>
<tr>
<th scope="col" style="text-align: center">Techskill</th>
<th scope="col" style="text-align: center">Action</th>
</tr>
</thead>
<tbody>
<% @employee.firms.each do |firm|%>
<tr>
<td style="text-align: center"><%= firm.techskill.name %></td>
<td style="text-align: center"><%=button_to "Delete",firm_path(firm),method: :delete , class:"btn btn-dark"%></td>
</tr>
<% end %>
</tbody>
</table>
</div>
<div class="row justify-content-center">
<%= button_to "Edit Employee",edit_employee_path,method: :get , class:"btn btn-dark"%></div><br>
<div class="row justify-content-center">
<%= button_to "Destroy Employee",employee_path,method: :delete , class:"btn btn-dark"%></div><br>
<div class="row justify-content-center">
<%= link_to "Go back",root_path%></div>
</div>

app/views/employees/update.html.erb
<h1>Employees#update</h1>
<p>Find me in app/views/employees/update.html.erb</p>

app/views/firms/create.html.erb
<h1>Firms#create</h1>
<p>Find me in app/views/firms/create.html.erb</p>

app/views/firms/destroy.html.erb
<h1>Firms#destroy</h1>
<p>Find me in app/views/firms/destroy.html.erb</p>

app/views/firms/index.html.erb
<h1>Firms#index</h1>
<p>Find me in app/views/firms/index.html.erb</p>

app/views/firms/new.html.erb
<div class="container">
<div class="row justify-content-center"><h1> Firm <h1>
</div><br>
<br>
<div class="row justify-content-center">
<p><h4> Choose your TechSkills</h4></p>
</div>
<br>
<br>
<div class="row justify-content-center">
<%= form_for @firm do|f|%>
<div class="form-group">
    <%= f.label :employee_id%><hr>&emsp;</hr>
    <%= f.collection_select :employee_id,Employee.all, :id, :name%>
</div>
<div class="form-group">
    <%= f.label :techskill_id%><hr>&emsp;</hr>
    <%= f.collection_select :techskill_id,Techskill.all, :id, :name%>
</div>
<div class="form-group">
    <%= f.label :name%><hr>&emsp;</hr>
    <%= f.text_field :name %>
</div>
<div class="form-group">
     <%= f.label :verified%><hr>&emsp;</hr>
    <%= f.text_field :verified %>
</div>
<br>
<br>
<div class="form-group">
    <%=f.submit 'Save Details',:class => 'btn btn-dark' %>
</div>
 <%end%>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EmployeeDb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet"   href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/techskills/create.html.erb
<h1>Techskills#create</h1>
<p>Find me in app/views/techskills/create.html.erb</p>

app/views/techskills/destroy.html.erb
<h1>Techskills#destroy</h1>
<p>Find me in app/views/techskills/destroy.html.erb</p>

app/views/techskills/index.html.erb
<h1>Techskills#index</h1>
<p>Find me in app/views/techskills/index.html.erb</p>

app/views/techskills/new.html.erb
<h1>Techskills#new</h1>
<p>Find me in app/views/techskills/new.html.erb</p>